//Base attributes for classes
const classesAttributes = {
    'berserk': {
        //Stats
        'life': 20.0,
        'lifeLevel': 3.0,
        'lifeRegen': 1.0,
        'lifeRegenLevel': 0.5,
        'mana': 2.0,
        'manaLevel': 0.3,
        'manaRegen': 0.5,
        'manaRegenLevel': 0.1,
        'strength': 12.0,
        'strengthLevel': 2.0,
        'agility': 6.0,
        'agilityLevel': 1.0,
        'intelligence': 2.0,
        'intelligenceLevel': 0.5,
        //Damage
        'physical': 5.0,
        'physicalLevel': 2.0,
        'ranged': 1.0,
        'rangedLevel': 0.5,
        'magical': 1.0,
        'magicalLevel': 0.5,
        'physicalAmplification': 0.0,
        'physicalAmplificationLevel': 0.5,
        'rangedAmplification': 0.0,
        'rangedAmplificationLevel': 0.0,
        'magicalAmplification': 0.0,
        'magicalAmplificationLevel': 0.0,
        'fireAmplification': 0.0,
        'fireAmplificationLevel': 0.0,
        'waterAmplification': 0.0,
        'waterAmplificationLevel': 0.0,
        'natureAmplification': 0.0,
        'natureAmplificationLevel': 0.0,
        'lightAmplification': 0.0,
        'lightAmplificationLevel': 0.0,
        'darkAmplification': 0.0,
        'darkAmplificationLevel': 0.0,
        //Defence
        'physicalResistence': 5.0,
        'physicalResistencelLevel': 1.0,
        'magicalResistence': 3.5,
        'magicalResistenceLevel': 0.7,
        'fireResistence': 0.0,
        'fireResistenceLevel': 0.0,
        'waterResistence': 0.0,
        'waterResistenceLevel': 0.0,
        'natureResistence': 0.0,
        'natureResistenceLevel': 0.0,
        'lightResistence': 0.0,
        'lightResistenceLevel': 0.0,
        'darkResistence': 0.0,
        'darkResistenceLevel': 0.0,
        'physicalResistenceAmplification': 0.0,
        'physicalResistenceAmplificationLevel': 0.0,
        'magicalResistenceAmplification': 0.0,
        'magicalResistenceAmplificationLevel': 0.0,
        'fireResistenceAmplification': 0.0,
        'fireResistenceAmplificationLevel': 0.0,
        'waterResistenceAmplification': 0.0,
        'waterResistenceAmplificationLevel': 0.0,
        'natureResistenceAmplification': 0.0,
        'natureResistenceAmplificationLevel': 0.0,
        'lightResistenceAmplification': 0.0,
        'lightResistenceAmplificationLevel': 0.0,
        'darkResistenceAmplification': 0.0,
        'darkResistenceAmplificationLevel': 0.0,
        //Skills and Buffs/Debuffs
        'skills': {},
        'buffs': {},
        'debuffs': {},
    }
}
//Base attributes for races
const raceAttributes = {
    'human': {
        //Stats
        'life': 0.0,
        'lifeLevel': 0.0,
        'lifeRegen': 0.0,
        'lifeRegenLevel': 0.0,
        'mana': 5.0,
        'manaLevel': 0.5,
        'manaRegen': 0.5,
        'manaRegenLevel': 0.3,
        'strength': 0.0,
        'strengthLevel': 0.0,
        'agility': 0.0,
        'agilityLevel': 0.0,
        'intelligence': 3.0,
        'intelligenceLevel': 1.0,
        //Damage
        'physical': 0.0,
        'physicalLevel': 0.0,
        'ranged': 0.0,
        'rangedLevel': 0.0,
        'magical': 0.0,
        'magicalLevel': 0.0,
        'physicalAmplification': 0.0,
        'physicalAmplificationLevel': 0.0,
        'rangedAmplification': 0.0,
        'rangedAmplificationLevel': 0.0,
        'magicalAmplification': 0.0,
        'magicalAmplificationLevel': 0.0,
        'fireAmplification': 0.0,
        'fireAmplificationLevel': 0.0,
        'waterAmplification': 0.0,
        'waterAmplificationLevel': 0.0,
        'natureAmplification': 0.0,
        'natureAmplificationLevel': 0.0,
        'lightAmplification': 5.0,
        'lightAmplificationLevel': 0.5,
        'darkAmplification': 0.0,
        'darkAmplificationLevel': 0.0,
        //Defence
        'physicalResistence': 0.0,
        'physicalResistencelLevel': 0.0,
        'magicalResistence': 0.0,
        'magicalResistenceLevel': 0.0,
        'fireResistence': 0.0,
        'fireResistenceLevel': 0.0,
        'waterResistence': 0.0,
        'waterResistenceLevel': 0.0,
        'natureResistence': 0.0,
        'natureResistenceLevel': 0.0,
        'lightResistence': 0.0,
        'lightResistenceLevel': 0.0,
        'darkResistence': 0.0,
        'darkResistenceLevel': 0.0,
        'physicalResistenceAmplification': 0.0,
        'physicalResistenceAmplificationLevel': 0.0,
        'magicalResistenceAmplification': 0.0,
        'magicalResistenceAmplificationLevel': 0.0,
        'fireResistenceAmplification': 0.0,
        'fireResistenceAmplificationLevel': 0.0,
        'waterResistenceAmplification': 0.0,
        'waterResistenceAmplificationLevel': 0.0,
        'natureResistenceAmplification': 0.0,
        'natureResistenceAmplificationLevel': 0.0,
        'lightResistenceAmplification': 0.0,
        'lightResistenceAmplificationLevel': 0.0,
        'darkResistenceAmplification': 0.0,
        'darkResistenceAmplificationLevel': 0.0,
        //Skills and Buffs/Debuffs
        'skills': {},
        'buffs': {},
        'debuffs': {},
    }
}

//Stats
const statusAttributes = {
    'lifeBonusPerStrength': 0.005,
    'manaBonusPerIntelligence': 0.005,
} 

module.exports.classesAttributes = classesAttributes;
module.exports.raceAttributes = raceAttributes;
module.exports.statusAttributes = statusAttributes;